# Generated by Django 2.1.7 on 2019-04-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserConfs', '0002_auto_20190408_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategories',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
