version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=raccoon
      - POSTGRES_PASSWORD=ahn6jii9AiX2Ahquee7u

  python:
    build: .
    command: bash -c "python manage.py makemigrations Auth UserConfs Booker && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
     -  .:/code

    depends_on:
      - db


  nginx:
    image: nginx:latest
    restart: always

    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./static:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx

    ports:
      - 80:80
      - 443:443

    depends_on:
      - python
