# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercategories',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userconfigs',
            name='user',
        ),
        migrations.DeleteModel(
            name='Costs',
        ),
        migrations.DeleteModel(
            name='UserCategories',
        ),
        migrations.DeleteModel(
            name='UserConfigs',
        ),
    ]
