# Generated by Django 2.1.7 on 2019-04-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserConfs', '0002_auto_20190408_1757'),
        ('Booker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheets',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sheets',
            name='user',
        ),
        migrations.AddField(
            model_name='sheets',
            name='sheetbase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserConfs.SheetBases'),
            preserve_default=False,
        ),
    ]
