# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-06 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0002_auto_20190225_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
