# Generated by Django 2.1.7 on 2019-04-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0003_sheets_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserConfs.UserCategories'),
        ),
    ]
