# Generated by Django 2.1.7 on 2019-05-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0004_auto_20190418_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheets',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
