# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0004_auto_20190306_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategories',
            name='user',
        ),
        migrations.AlterField(
            model_name='activities',
            name='descr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sheets',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='UserCategories',
        ),
    ]
