# Generated by Django 2.1.7 on 2019-05-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0005_auto_20190522_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='origin_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
