# Generated by Django 2.1.7 on 2019-06-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0006_activities_origin_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='pinned',
        ),
    ]
