# Generated by Django 2.1.7 on 2019-06-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0007_remove_activities_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheets',
            name='name',
            field=models.CharField(default='some sheet', max_length=100),
            preserve_default=False,
        ),
    ]
