# Generated by Django 2.1.7 on 2019-07-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0009_auto_20190623_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='descr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='name',
            field=models.TextField(),
        ),
    ]
