# Generated by Django 2.1.7 on 2019-07-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0010_auto_20190709_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='descr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
