# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20190207_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
